steps:
  - id: "Rodando docker-compose"
    name:  'gcr.io/$PROJECT_ID/docker-compose:1.25.5'
    args: ['-f', 'docker-compose.cloudbuid.yml', 'up', '-d']
  
  - id: "Rodando composer"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'myapp', 'composer', 'install']

  - id: "Copiando .env"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'myapp', 'cp', '.env.example', '.env']
  
  - id: "Rodando key:generate"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'myapp', 'php', 'artisan', 'key:generate']

  - id: "Rodando migrations"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'myapp', 'php', 'artisan', 'migrate']

  - id: "Rodando phpunit"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'myapp', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml']